version: '2'
services:
  main:
    build: .
    volumes:
         - ./test-results:/home/node/invoice/test-results
    environment:
      MOCHA_FILE: test-results/unit-tests.xml
    command: 'npm run dev'
