FROM node:6-alpine
MAINTAINER OpusCapita

WORKDIR /var/tmp/base

COPY package.json .

ENV NODE_ENV=development

RUN apk add --no-cache rsync curl ; npm set progress=false && npm install && npm cache clean
