version: '2'
services:
  main:
#    build: .
    image: opuscapita/invoice:dev
    volumes:
         - .:/home/node/invoice
    environment:
      MOCHA_FILE: test-results.xml
    command: 'npm run dev'
