version: '2'
services:
  main:
    image: opuscapita/invoice:dev
    environment:
      MOCHA_FILE: test-results/unit-tests.xml
    volumes:
     - ./test-results:/home/node/invoice/test-results
    command: 'npm run dev'
